arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false  # Set to true if you want files in .dart_tool instead
nullable-getter: false    # Set this according to your preference