// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'prostuti';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ALERT_CIRCLE_DARK = 'assets/icons/alert-circle_dark.svg';
  static const String AWARD_01_DARK = 'assets/icons/award-01_dark.svg';
  static const String BOOKS_01 = 'assets/icons/books-01.svg';
  static const String CATALOGUE = 'assets/icons/catalogue.svg';
  static const String CATALOGUE_DARK = 'assets/icons/catalogue_dark.svg';
  static const String CATEGORY_DARK = 'assets/icons/category_dark.svg';
  static const String CROWN = 'assets/icons/crown.svg';
  static const String CROWN_DARK = 'assets/icons/crown_dark.svg';
  static const String CUSTOMER_SUPPORT_DARK = 'assets/icons/customer-support_dark.svg';
  static const String FAVOURITE_DARK = 'assets/icons/favourite_dark.svg';
  static const String HELP_CIRCLE = 'assets/icons/help-circle.svg';
  static const String HELP_CIRCLE_DARK = 'assets/icons/help-circle_dark.svg';
  static const String LANGUAGE_SQUARE = 'assets/icons/language-square.svg';
  static const String LANGUAGE_SQUARE_DARK = 'assets/icons/language-square_dark.svg';
  static const String MOON_ECLIPSE = 'assets/icons/moon-eclipse.svg';
  static const String MOON_ECLIPSE_DARK = 'assets/icons/moon-eclipse_dark.svg';
  static const String SECURITY = 'assets/icons/security.svg';
  static const String SECURITY_DARK = 'assets/icons/security_dark.svg';
  static const String STAR = 'assets/icons/star.svg';
  static const String USER_DARK = 'assets/icons/user_dark.svg';
}
