// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class LibRes {
  LibRes._();

  static const String PLUGIN_NAME = 'prostuti';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String APP_BN = 'lib/l10n/app_bn.arb';
  static const String APP_EN = 'lib/l10n/app_en.arb';
}
